apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
  namespace: fraud-team
  labels:
    app: fraud-service
    team: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
        team: fraud
    spec:
      containers:
        - name: fraud-service
          image: 388691194728.dkr.ecr.us-east-1.amazonaws.com/anthony-assessment4-fraud:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fraud-config
            - secretRef:
                name: fraud-service-secret
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
